from cookbook import Enum

class EventType(Enum):
    pass


LEFT_MOUSE_BUTTON_DOWN = EventType("LEFT_MOUSE_BUTTON_DOWN")
LEFT_MOUSE_BUTTON_UP = EventType("LEFT_MOUSE_BUTTON_UP")
RIGHT_MOUSE_BUTTON_DOWN = EventType("RIGHT_MOUSE_BUTTON_DOWN")
RIGHT_MOUSE_BUTTON_UP = EventType("RIGHT_MOUSE_BUTTON_UP")
MOUSE_MOTION = EventType("MOUSE_MOTION")

